sudo: false
language: perl
matrix:
    fast_finish: true
perl:
   - '5.24'
   - '5.14'
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
   - sudo apt-get update -qq
   - sudo apt-get install software-properties-common -y -qq
   - sudo add-apt-repository -y ppa:ethereum/ethereum
   - sudo apt-get update -qq
   - sudo apt-get install geth -y -qq
   - mkdir -p ~/.ethereum
   - geth --dev --rpc  --rpcport 8545 --rpcaddr 127.0.0.1 --rpcapi="eth,net,web3,personal,debug" --mine --minerthreads=1 &
install:
   - cpanm --quiet --notest Dist::Zilla Dist::Zilla::App::Command::cover App::cpm Devel::Cover::Report::Codecov https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-7.29.tar.gz https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.30.tar.gz
   - cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil authordeps --missing)
   - cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil listdeps --author --missing)
script:
   - dzil smoke --release --author && dzil cover -test -report codecov && dzil xtest:
